spring:
  datasource:
    username: sa
    password: sa
    url:  jdbc:sqlserver://localhost:1433;DatabaseName=medical
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.ll.medical.data.jpa.ImprovedNamingStrategy
    database: SQLSERVER
    properties:
      hibernate.default_schema: dbo
server:
  port: 80
